using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BackgroundMusic : MonoBehaviour
{
    AudioSource audioSource;
    // Start is called before the first frame update
    void Start()
    {
     audioSource = GetComponent<AudioSource>();
        audioSource.Play();
    }

    private void Update()
    {
        if(Input.GetKeyDown(KeyCode.M)) 
        { 
            if (audioSource.isPlaying)
            {
                audioSource.Pause();
            }
            else
            {
                audioSource.Play();
            }
        }
    }
}
